modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/ProgrammerLP/Create-Train-Lights/issues"
license = "AGPL-3"

[[mods]]
modId = "ctl"
version = "${version}"
displayName = "Create: Train Lights"
authors = "ProgrammerLP"
description = '''
Create addon that adds custom interior and head tail lights for trains that automatically switch between headlight and tail light depending on the direction of travel.
'''
logoFile = "mod_icon.png"

[[dependencies.ctl]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ctl]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ctl]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ctl]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,]"
ordering="NONE"
side="BOTH"