modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ProgrammerLP/Create-Train-Lights/issues"
license = "AGPL-3"

[[mods]]
modId = "ctl"
version = "${version}"
displayName = "Create: Train Lights"
authors = "ProgrammerLP"
description = '''
Create addon that adds custom interior and head tail lights for trains that automatically switch between headlight and tail light depending on the direction of travel.
'''
logoFile = "mod_icon.png"

[[dependencies.ctl]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ctl]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ctl]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ctl]]
modId = "create"
type = "required"
versionRange = "[6.0.6,]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "ctl.mixins.json"